name: Buf CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Linux arm64 is not supported by Homebrew:
  # https://docs.brew.sh/Homebrew-on-Linux#arm-unsupported
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "DONE"
          brew doctor
          brew install --build-from-source Formula/buf.rb
          buf --version
  darwin-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install --build-from-source Formula/buf.rb
      - run: buf --version
  darwin-x86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: brew install --build-from-source Formula/buf.rb
      - run: buf --version
