name: Create Buf Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release (eg x.y.z)
env:
  VERSION: ${{ github.event.inputs.version }}
jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v3
      - name: Update formula
        run: |
          # Darwin arm64
          curl -LO https://github.com/bufbuild/buf/releases/download/${VERSION}/buf-${VERSION}-Darwin-arm64
          SHA256=$(shasum -a 256 bufstream-$VERSION-Darwin-arm64 | awk '{print $1}')
          sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/buf.rb
          sed -i "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/buf.rb
          sed -i "s/\"darwin-arm64\" => \".*\"/\"darwin-arm64\" => \"$SHA256\"/" Formula/buf.rb
          # Darwin x86_64
          curl -LO https://github.com/bufbuild/buf/releases/download/${VERSION}/buf-${VERSION}-Darwin-x86_64
          SHA256=$(shasum -a 256 bufstream-$VERSION-Darwin-x86_64 | awk '{print $1}')
          sed -i "s/\"darwin-x86_64\" => \".*\"/\"darwin-x86_64\" => \"$SHA256\"/" Formula/buf.rb
          # Linux arm64
          curl -LO https://github.com/bufbuild/buf/releases/download/${VERSION}/buf-${VERSION}-Linux-aarch64
          SHA256=$(shasum -a 256 bufstream-$VERSION-Linux-aarch64 | awk '{print $1}')
          sed -i "s/\"linux-arm64\" => \".*\"/\"linux-arm64\" => \"$SHA256\"/" Formula/buf.rb
          # Linux x86_64
          curl -LO https://github.com/bufbuild/buf/releases/download/${VERSION}/buf-${VERSION}-Linux-x86_64
          SHA256=$(shasum -a 256 bufstream-$VERSION-Linux-x86_64 | awk '{print $1}')
          sed -i "s/\"linux-x86_64\" => \".*\"/\"linux-x86_64\" => \"$SHA256\"/" Formula/buf.rb
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
