name: Buf CI
on:
  push:
    paths:
      - 'proto/**'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
    paths:
      - 'proto/**'
permissions:
  contents: read
  pull-requests: write
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@1efb02dd3dfcc834347df3fba562d0238b94ab0c
        with:
          token: ${{ secrets.BUF_TOKEN }}
