name: Buf CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        #        with:
        #          fetch-depth: 1
      - uses: bufbuild/buf-action@main
        with:
          token: ${{ secrets.BUF_TOKEN }}
          #push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/staging') }}
