name: Buf action CI
on:
  push:
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "HELLO"
          git status
          git ls-remote --heads --tags
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-cache-${{ hashFiles('Makefile') }}
          restory-keys: ${{ runner.os }}-go-cache-
      - run: go install github.com/bufbuild/buf/cmd/buf@ed/fixGitMetadataPseudorefs
        env:
          GOPROXY: direct
      - run: |
          buf --version
          buf push --error-format github-actions --create --git-metadata
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
