name: Buf action CI
on:
  push:
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "HELLO"
          git status
          git fetch --tags origin
