name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_REF_A: ${{ github.ref }}
        GITHUB_REF_NAME_A: ${{ github.ref_NAME }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        env
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@main
        with:
          token: ${{ secrets.BUF_TOKEN }}
