name: Buf CI
on:
  push:
  #pull_request:
  #  types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@main
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip lint')
          format: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip format')
          breaking: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip breaking')
  buf_setup_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - run: buf --version
